hello_app/config/routes.rb
Rails.application.routes.draw do
  resources :micro_posts
  resources :users
  get 'home/index'
end

hello_app/app/models/micro_post.rb
class MicroPost < ApplicationRecord
    belongs_to :user
    validates :content, length: { maximum: 10 },  presence:true
    validates :user_id, length: { maximum: 10 },  presence:true
end

hello_app/app/models/user.rb
class User < ApplicationRecord
  validates :name, length: { maximum: 10 },  presence:true
  has_many :micro_post
end

hello_app/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  def hello
    render text:"Hello Rails"
  end
end

hello_app/app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    render text:"Hello Rails"
  end
end

hello_app/app/controllers/micro_posts_controller.rb
class MicroPostsController < ApplicationController
  before_action :set_micro_post, only: [:show, :edit, :update, :destroy]

  # GET /micro_posts
  # GET /micro_posts.json
  def index
    @micro_posts = MicroPost.all
  end

  # GET /micro_posts/1
  # GET /micro_posts/1.json
  def show
  end

  # GET /micro_posts/new
  def new
    @micro_post = MicroPost.new
  end

  # GET /micro_posts/1/edit
  def edit
  end

  # POST /micro_posts
  # POST /micro_posts.json
  def create
    @micro_post = MicroPost.new(micro_post_params)

    respond_to do |format|
      if @micro_post.save
        format.html { redirect_to @micro_post, notice: 'Micro post was successfully created.' }
        format.json { render :show, status: :created, location: @micro_post }
      else
        format.html { render :new }
        format.json { render json: @micro_post.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /micro_posts/1
  # PATCH/PUT /micro_posts/1.json
  def update
    respond_to do |format|
      if @micro_post.update(micro_post_params)
        format.html { redirect_to @micro_post, notice: 'Micro post was successfully updated.' }
        format.json { render :show, status: :ok, location: @micro_post }
      else
        format.html { render :edit }
        format.json { render json: @micro_post.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /micro_posts/1
  # DELETE /micro_posts/1.json
  def destroy
    @micro_post.destroy
    respond_to do |format|
      format.html { redirect_to micro_posts_url, notice: 'Micro post was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_micro_post
      @micro_post = MicroPost.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def micro_post_params
      params.require(:micro_post).permit(:content, :user_id)
    end
end

hello_app/app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]

  # GET /users
  # GET /users.json
  def index
    @users = User.all
  end

  # GET /users/1
  # GET /users/1.json
  def show
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        format.html { redirect_to @user, notice: 'User was successfully created.' }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url, notice: 'User was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def user_params
      params.require(:user).permit(:name, :email)
    end
end

hello_app/app/helpers/home_helper.rb
module HomeHelper
end

hello_app/app/helpers/micro_posts_helper.rb
module MicroPostsHelper
end

hello_app/app/helpers/users_helper.rb
module UsersHelper
end

hello_app/app/views/home/index.html.erb
<h1>Home#index</h1>
<p>Find me in app/views/home/index.html.erb</p>

hello_app/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>HelloApp</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

hello_app/app/views/micro_posts/_form.html.erb
<%= form_for(micro_post) do |f| %>
  <% if micro_post.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(micro_post.errors.count, "error") %> prohibited this micro_post from being saved:</h2>

      <ul>
      <% micro_post.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :content %>
    <%= f.text_area :content %>
  </div>

  <div class="field">
    <%= f.label :user_id %>
    <%= f.number_field :user_id %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

hello_app/app/views/micro_posts/edit.html.erb
<h1>Editing Micro Post</h1>

<%= render 'form', micro_post: @micro_post %>

<%= link_to 'Show', @micro_post %> |
<%= link_to 'Back', micro_posts_path %>

hello_app/app/views/micro_posts/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Micro Posts</h1>

<table>
  <thead>
    <tr>
      <th>Content</th>
      <th>User</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @micro_posts.each do |micro_post| %>
      <tr>
        <td><%= micro_post.content %></td>
        <td><%= micro_post.user_id %></td>
        <td><%= link_to 'Show', micro_post %></td>
        <td><%= link_to 'Edit', edit_micro_post_path(micro_post) %></td>
        <td><%= link_to 'Destroy', micro_post, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Micro Post', new_micro_post_path %>

hello_app/app/views/micro_posts/new.html.erb
<h1>New Micro Post</h1>

<%= render 'form', micro_post: @micro_post %>

<%= link_to 'Back', micro_posts_path %>

hello_app/app/views/micro_posts/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Content:</strong>
  <%= @micro_post.content %>
</p>

<p>
  <strong>User:</strong>
  <%= @micro_post.user_id %>
</p>

<%= link_to 'Edit', edit_micro_post_path(@micro_post) %> |
<%= link_to 'Back', micro_posts_path %>

hello_app/app/views/users/_form.html.erb
<%= form_for(user) do |f| %>
  <% if user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% user.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %>
    <%= f.text_field :name %>
  </div>

  <div class="field">
    <%= f.label :email %>
    <%= f.text_field :email %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

hello_app/app/views/users/edit.html.erb
<h1>Editing User</h1>

<%= render 'form', user: @user %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>

hello_app/app/views/users/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Users</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Email</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= user.name %></td>
        <td><%= user.email %></td>
        <td><%= link_to 'Show', user %></td>
        <td><%= link_to 'Edit', edit_user_path(user) %></td>
        <td><%= link_to 'Destroy', user, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New User', new_user_path %>

hello_app/app/views/users/new.html.erb
<h1>New User</h1>

<%= render 'form', user: @user %>

<%= link_to 'Back', users_path %>

hello_app/app/views/users/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @user.name %>
</p>

<p>
  <strong>Email:</strong>
  <%= @user.email %>
</p>

<%= link_to 'Edit', edit_user_path(@user) %> |
<%= link_to 'Back', users_path %>